
version: 2
jobs:
  check-filenames:
    docker:
      - image: circleci/python:3.7.0-stretch
    steps:
      - checkout
      - run:
          name: Check filenames
          command: |
            ./scripts/check_filenames.sh

workflows:
  version: 2
  test:
    jobs:
      - check-filenames
